github.com:
    users:
        koagonzalo11:
            oauth_token: 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
        "":
            oauth_token: github_pat_11BJI2WIQ04o36uKRYZQpF_6x1puQSf8UiayOZXqYXxxXiVx8FYuLSti06gsTzjhNxVCWE6NNCnbU2gnYC
    git_protocol: ssh
    user:
    oauth_token: github_pat_11BJI2WIQ04o36uKRYZQpF_6x1puQSf8UiayOZXqYXxxXiVx8FYuLSti06gsTzjhNxVCWE6NNCnbU2gnYC
